In [1]:
import numpy as np 
a= np.array(([1,2],[3,4]))
b=a.tolist ()
print (a)
print (b)

[[1 2]
 [3 4]]
[[1, 2], [3, 4]]


In [2]:
import numpy as np
a= np.array(([1,2,3],[4,5,6],[7,8,9]))
print (a)
b = a[0,0]+a[1,1]+a[2,2]
print (b)
c= np.trace(a)
print (c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15
15


In [3]:
import numpy as np
a= np.array(( [1,2,3]
             ,[4,5,6]
             ,[7,8,9]))
x= 5
b= np.where (a > x)
print (a[b])
print (a[a>x])

[6 7 8 9]
[6 7 8 9]


In [4]:
import numpy as np
a = np.array(([4,4],[4,4]))
b = np.array (([3,3],[3,3]))
c = np.add(a,b)
print (c)

[[7 7]
 [7 7]]


In [5]:
import numpy as np
a = np.array(([1,2],[3,4]))
b= np.mean(a[0,:])
c = np.mean(a[1,:])
d= b - c
print (d)

-2.0
